### ISSUE TITLE
Quizizz Websocket Update

### ISSUE THREAD

**Issue by avivkeller** [theusaf/quizziz.js#9]
Hello, Quizizz updated their API to v4, and their web sockets have updated as well.
They now use "_gsocket" in their links instead of "socket.io", but that is still accessible.
Their new link that the service uses is "https://socket.quizizz.com/_gsocket/sockUpg/?experiment=authRevamp&EIO=4&transport=polling&t=?????". Each time I run a Quizizz, the "t" variable is different, and I can't figure out how it is generated. Please update your script to generate a "t" variable.

**Comment by theusaf** [comment]
I don't know how the t variable is created, but it doesn't seem too important. Removing the t variable still results in a successful response.

Edit: currently looking at socket.io's documentation to see if it mentions this anywhere.

quizizz.js is somewhat low on my priority list currently, so I won't be able to do much direct updates, but if you make issues on it, I will see if I can solve the issue.

**Comment by theusaf** [comment]
https://stackoverflow.com/questions/48633145/what-is-the-t-query-parameter-in-a-socket-io-handshake

Not important. Only used to bypass the cache, so it can be set to a random value.

**Comment by theusaf** [comment]
I'm considering just using socket.io directly, instead of trying to simulate socket.io using plain WebSockets.

**Comment by avivkeller** [comment]
I see

**Comment by avivkeller** [comment]
I tried it with socket.io-client, and so far, no luck. The socket disconnects instantly, but does not return an error.

**Comment by avivkeller** [comment]
Could I be added as a contributor to this project? With edit access, it will make fixing bugs and updating code easier.
(Add contributors under access control in settings)

**Comment by theusaf** [comment]
Sure!

Edit: I've invited you to the repo.

**Comment by avivkeller** [comment]
Thanks!

**Comment by avivkeller** [comment]
Some useful info: Quizizz uses socket.io with extra parameters like the URL. Oddly enough, I can not connect to the socket using the same parameters.

**Comment by pxtrez** [comment]
this "t" parameter is genereted by "yeast"
